### PR TITLE
Korean translation update

### PR DESCRIPTION
**Pull request by hwangsihu**

### CODE REVIEW

**Comment by josephsl** [comment]
Hello,

We do not accept localization files via pull requests. Please send nvda.o files to NVDA translatins list or to Korean translators directly. Thank you (closing).

**Comment by hwangsihu** [comment]
Sorry, but could you please tell me the site? I don't know where it is.

**Comment by josephsl** [comment]
https://groups.io/g/nvda-translations

**Comment by hwangsihu** [comment]
Ok thanks

**Pull request closed without merging**
